name: Node.js Package

on:
  workflow_dispatch:

  release:
    types: [created]

jobs:
  publish-gpr:
    name: Publish CLI

    if: startsWith(github.ref, 'refs/tags/cli-')

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: ./cli

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - run: |
          npm ci
          npm run test
          npm run webpack
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}