name: Release and Publish to the Marketplace and Open VSX

on:
  workflow_dispatch:

  release:
    types: [created]

jobs:
  release:
    name: Publish Extension

    if: startsWith(github.ref, 'refs/tags/vs-')

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: ./vs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install NPM Dependencies
        run: |
          npm install
          npm install -g vsce ovsx

      - name: Publish to Open VSX
        run: npx ovsx publish -p $OPENVSX_TOKEN
        env:
          OPENVSX_TOKEN: ${{ secrets.OPENVSX_TOKEN }}

      - name: Publish to Marketplace
        run: vsce publish -p $PUBLISHER_TOKEN
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
