name: Release CLI and Extension

on:
  workflow_dispatch:

  release:
    types: [created]

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Publish CLI
        working-directory: ./cli
        run: |
          npm ci
          npm run test
          npm run webpack
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Install NPM Dependencies
        working-directory: ./vs
        run: |
          npm install
          npm install -g vsce ovsx

      - name: Publish to Open VSX
        working-directory: ./vs
        run: npx ovsx publish -p $OPENVSX_TOKEN
        env:
          OPENVSX_TOKEN: ${{ secrets.OPENVSX_TOKEN }}

      - name: Publish to Marketplace
        working-directory: ./vs
        run: vsce publish -p $PUBLISHER_TOKEN
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}