name: Test with Vitest

on:
  workflow_dispatch:

  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18.x]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./cli
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Dependencies
        run: npm install

      - name: Run Test
        run: npm run test

      - name: Pack
        run: |
          npm run webpack
          npm pack
